// import {
//   log,
//   useBox,
//   green,
//   customHelp,
//   whiteUnderline,
//   red,
//   gray,
//   dimWhite,
//   cyan,
//   wrongCommandAlert,
//   noCommandAlert,
//   spinner,
//   useHelpAlert,
//   showEndMessage,
//   fileNotDetectedAlert,
//   unrecognizedFileAlert,
//   checkCommunityStandardMet,
//   castElementsToFormatedString,
// } from '../alerts';
