  language: node_js
  node_js:
    - "v16.15.0"
  cache:
    directories:
      - node_modules
  install:
    - yarn
  script:
    -  yarn test
  after_success:
    - nyc report --reporter=text-lcov | coveralls
